knp_paginator:
    page_range: 6                      # number of links shown in the pagination menu
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results
        filter_field_name: filterField # filter field query parameter name
        filter_value_name: filterValue # filter value query parameter name
    template:
        pagination: 'pagination/custom_pagination.html.twig'
 