security:
    enable_authenticator_manager: true

    # Password hasher (or encoder, depending on your Symfony version)
    # password_hashers:
    #     App\Entity\User: 'auto'

    # providers:
    #     app_user_provider:
    #         entity:
    #             class: App\Entity\User
    #             property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            # user_checker: App\Security\UserChecker
            lazy: true
            # provider: app_user_provider
            # custom_authenticators:
                # - App\Security\LoginAuthenticator
            # logout:
            #     path: /logout
            #     invalidate_session: true
            # remember_me:
            #     secret: '%kernel.secret%'
            #     lifetime: 604800   # one week (in seconds)
            #     path: /
            #     always_remember_me: true

    # role_hierarchy:
    #     ROLE_FREELANCER: []
    #     ROLE_RECRUTEUR: []
    #     ROLE_ADMIN: []

    # access_control:
    #     - { path: ^/login, roles: PUBLIC_ACCESS }
    #     - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/admin, roles: ROLE_ADMIN }
    #     - { path: ^/recruteur, roles: ROLE_RECRUTEUR }
    #     - { path: ^/freelancer, roles: ROLE_FREELANCER }
    #     - { path: ^/, roles: IS_AUTHENTICATED_FULLY }


# Separate configuration for test environment
when@test:
    security:
        password_hashers:
        # Use native password hasher, which auto-selects and migrates the best
        # possible hashing algorithm (starting from Symfony 5.3 this is "bcrypt")
        #Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
               # algorithm: auto
                #cost: 4
                #time_cost: 3
                #memory_cost: 10
                Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
