<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Favourite' => [parent::class, 'Favourite', null],
        "\0".parent::class."\0".'Rating' => [parent::class, 'Rating', null],
        "\0".parent::class."\0".'coachinglicense' => [parent::class, 'coachinglicense', null],
        "\0".parent::class."\0".'createdat' => [parent::class, 'createdat', null],
        "\0".parent::class."\0".'dateofbirth' => [parent::class, 'dateofbirth', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'events' => [parent::class, 'events', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'orders' => [parent::class, 'orders', null],
        "\0".parent::class."\0".'paniers' => [parent::class, 'paniers', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'phonenumber' => [parent::class, 'phonenumber', null],
        "\0".parent::class."\0".'position' => [parent::class, 'position', null],
        "\0".parent::class."\0".'profilepicture' => [parent::class, 'profilepicture', null],
        "\0".parent::class."\0".'reclamations' => [parent::class, 'reclamations', null],
        "\0".parent::class."\0".'reset_code' => [parent::class, 'reset_code', null],
        "\0".parent::class."\0".'reset_code_expiry' => [parent::class, 'reset_code_expiry', null],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null],
        "\0".parent::class."\0".'team' => [parent::class, 'team', null],
        "\0".parent::class."\0".'tournois' => [parent::class, 'tournois', null],
        "\0".parent::class."\0".'updatedat' => [parent::class, 'updatedat', null],
        'Favourite' => [parent::class, 'Favourite', null],
        'Rating' => [parent::class, 'Rating', null],
        'coachinglicense' => [parent::class, 'coachinglicense', null],
        'createdat' => [parent::class, 'createdat', null],
        'dateofbirth' => [parent::class, 'dateofbirth', null],
        'email' => [parent::class, 'email', null],
        'events' => [parent::class, 'events', null],
        'firstname' => [parent::class, 'firstname', null],
        'id' => [parent::class, 'id', null],
        'lastname' => [parent::class, 'lastname', null],
        'orders' => [parent::class, 'orders', null],
        'paniers' => [parent::class, 'paniers', null],
        'password' => [parent::class, 'password', null],
        'phonenumber' => [parent::class, 'phonenumber', null],
        'position' => [parent::class, 'position', null],
        'profilepicture' => [parent::class, 'profilepicture', null],
        'reclamations' => [parent::class, 'reclamations', null],
        'reset_code' => [parent::class, 'reset_code', null],
        'reset_code_expiry' => [parent::class, 'reset_code_expiry', null],
        'role' => [parent::class, 'role', null],
        'team' => [parent::class, 'team', null],
        'tournois' => [parent::class, 'tournois', null],
        'updatedat' => [parent::class, 'updatedat', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
