<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Team extends \App\Entity\Team implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'logoPath' => [parent::class, 'logoPath', null],
        "\0".parent::class."\0".'matches' => [parent::class, 'matches', null],
        "\0".parent::class."\0".'modeJeu' => [parent::class, 'modeJeu', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'nombreJoueurs' => [parent::class, 'nombreJoueurs', null],
        "\0".parent::class."\0".'rankings' => [parent::class, 'rankings', null],
        "\0".parent::class."\0".'tournoi' => [parent::class, 'tournoi', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        'categorie' => [parent::class, 'categorie', null],
        'id' => [parent::class, 'id', null],
        'logoPath' => [parent::class, 'logoPath', null],
        'matches' => [parent::class, 'matches', null],
        'modeJeu' => [parent::class, 'modeJeu', null],
        'nom' => [parent::class, 'nom', null],
        'nombreJoueurs' => [parent::class, 'nombreJoueurs', null],
        'rankings' => [parent::class, 'rankings', null],
        'tournoi' => [parent::class, 'tournoi', null],
        'users' => [parent::class, 'users', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
