<?php

namespace ContainerIk7pCDG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7jHBs0DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7jHBs0D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7jHBs0D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminDashboradController::tables' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\OrderController::delete' => ['privates', '.service_locator.fPqsAYY', 'get_ServiceLocator_FPqsAYYService', true],
            'App\\Controller\\OrderController::edit' => ['privates', '.service_locator.fPqsAYY', 'get_ServiceLocator_FPqsAYYService', true],
            'App\\Controller\\OrderController::index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\OrderController::new' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.an3gMCH', 'get_ServiceLocator_An3gMCHService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.an3gMCH', 'get_ServiceLocator_An3gMCHService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ShopController::addToCart' => ['privates', '.service_locator.an3gMCH', 'get_ServiceLocator_An3gMCHService', true],
            'App\\Controller\\ShopController::cart' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ShopController::index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ShopController::removeFromCart' => ['privates', '.service_locator.3zNo1H.', 'get_ServiceLocator_3zNo1H_Service', true],
            'App\\Controller\\ShopController::show' => ['privates', '.service_locator.an3gMCH', 'get_ServiceLocator_An3gMCHService', true],
            'App\\Controller\\ShopLoginController::login' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ShopLoginController::register' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\TeamHomeController::index' => ['privates', '.service_locator.5kCoGeN', 'get_ServiceLocator_5kCoGeNService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminDashboradController:tables' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\OrderController:delete' => ['privates', '.service_locator.fPqsAYY', 'get_ServiceLocator_FPqsAYYService', true],
            'App\\Controller\\OrderController:edit' => ['privates', '.service_locator.fPqsAYY', 'get_ServiceLocator_FPqsAYYService', true],
            'App\\Controller\\OrderController:index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\OrderController:new' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.an3gMCH', 'get_ServiceLocator_An3gMCHService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.an3gMCH', 'get_ServiceLocator_An3gMCHService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ShopController:addToCart' => ['privates', '.service_locator.an3gMCH', 'get_ServiceLocator_An3gMCHService', true],
            'App\\Controller\\ShopController:cart' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ShopController:index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ShopController:removeFromCart' => ['privates', '.service_locator.3zNo1H.', 'get_ServiceLocator_3zNo1H_Service', true],
            'App\\Controller\\ShopController:show' => ['privates', '.service_locator.an3gMCH', 'get_ServiceLocator_An3gMCHService', true],
            'App\\Controller\\ShopLoginController:login' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ShopLoginController:register' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\TeamHomeController:index' => ['privates', '.service_locator.5kCoGeN', 'get_ServiceLocator_5kCoGeNService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminDashboradController::tables' => '?',
            'App\\Controller\\OrderController::delete' => '?',
            'App\\Controller\\OrderController::edit' => '?',
            'App\\Controller\\OrderController::index' => '?',
            'App\\Controller\\OrderController::new' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ShopController::addToCart' => '?',
            'App\\Controller\\ShopController::cart' => '?',
            'App\\Controller\\ShopController::index' => '?',
            'App\\Controller\\ShopController::removeFromCart' => '?',
            'App\\Controller\\ShopController::show' => '?',
            'App\\Controller\\ShopLoginController::login' => '?',
            'App\\Controller\\ShopLoginController::register' => '?',
            'App\\Controller\\TeamHomeController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminDashboradController:tables' => '?',
            'App\\Controller\\OrderController:delete' => '?',
            'App\\Controller\\OrderController:edit' => '?',
            'App\\Controller\\OrderController:index' => '?',
            'App\\Controller\\OrderController:new' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ShopController:addToCart' => '?',
            'App\\Controller\\ShopController:cart' => '?',
            'App\\Controller\\ShopController:index' => '?',
            'App\\Controller\\ShopController:removeFromCart' => '?',
            'App\\Controller\\ShopController:show' => '?',
            'App\\Controller\\ShopLoginController:login' => '?',
            'App\\Controller\\ShopLoginController:register' => '?',
            'App\\Controller\\TeamHomeController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
