<?php

namespace ContainerIk7pCDG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_An3gMCHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.an3gMCH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.an3gMCH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'product' => ['privates', '.errored..service_locator.an3gMCH.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.an3gMCH": it needs an instance of "App\\Entity\\Product" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'product' => 'App\\Entity\\Product',
        ]);
    }
}
