<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIk7pCDG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIk7pCDG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIk7pCDG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIk7pCDG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIk7pCDG\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ik7pCDG',
    'container.build_id' => '144ae495',
    'container.build_time' => 1744886541,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIk7pCDG');
